name: couchdbkit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [ "3.9" ]
        django-version: [ "3.2.*", "4.2.*" ]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          pip install django==${{ matrix.django-version }} 
          pip install -r requirements_dev.txt
          python setup.py install
      - name: start up couch
        run: |
          docker run -d --name couchdb-cluster -p 5984:5984 \
          -v $(pwd)/data:/usr/src/couchdb/dev/lib/ \
          klaemo/couchdb:2.0-dev \
          --with-admin-party-please --with-haproxy -n 1
      - name: wait for couch to start
        run: |
          while:
          do
            curl http://localhost:5984/${db_name} -sv 2>&1 | grep '^< HTTP/.* 200 OK' && break || continue
            sleep 1
          done
      - name: run tests
        run: |
          python setup.py test
